### ISSUE TITLE
Enhancement: Support ArxSmartPtr's shared_ptr objects (Ported from BOOST to standalone Arduino)

### ISSUE THREAD

**Issue by NachtRaveVL** [davetcc/SimpleCollections#8]
Would love to see added support for https://github.com/hideakitai/ArxSmartPtr -- as of this moment I believe the issue is that you are one-off of a level of dereferencing, where you have a pointer to type T and then you invoke ->getKey(), which in the case of shared_ptr doesn't utilize its operator->() call since at that point it was reinterpret casted to a pointer to the shared_ptr object, thus attempting to call the shared_ptr's getKey() method (which it doesn't have).

I believe this may just be a limitation of your current design in general, tho, as it would seem it does about the same with a pointer based type, as well.

I was thinking about this exact issue actually the other day actually, and one way to implement support for this is to distinguish between pointer types and value types at the class level (where each class could do the appropriate amount of dereferencing based on T being value type or pointer/shared_ptr type) - I've seen interesting variations on splitting classes into two subclasses based on various properties. ArduinoJSON library, for instance, won't allocate a memory pool for a read-only object (since it won't be modified), but it will for the writeable object (since it might) - doesn't use const but it does suffix the name the object with Const. Even language like ObjC also do this, by having a MutableArray being write-enabled and Array being read-only (with MutableArray inheriting from Array).

Anyways, I realize it's a big ask, but it would be awesome to see support for such things added. I've included a test program illustrating the compilation error I get when I try to use a shared_ptr object directly.

```
#include <Arduino.h>
#include <SimpleCollections.h>
#include <ArxSmartPtr.h>
#include <assert.h>
using namespace std;

class TestClass {
public:
  TestClass(int key) : _key(key) {;}  
  int getKey() const { return _key; }
private:
  int _key;
};

void setup() {
  BtreeList<int, shared_ptr<TestClass> > list;
  auto instance = make_shared<TestClass>(0);
  list.add(instance);
  auto instanceRet = list.getByKey(0);
  assert(instance.get() == (*instanceRet).get());
}

void loop() {}

```

**Comment by davetcc** [comment]
In order to understand simple collections fully, we have to understand what's happening underneath. The template part that you use is just a very simple wrapper around some fairly nasty non-templatized C code dealing with raw memory locations. It uses the various operators (equals, copy constructor) to move things safely, but at the end of the day it is purposely quite limited to keep the memory footprint very small.

If we look at the why for the library, it is to allow small boards such as Uno (AVR), which don't really have room for STL to be able to store ordered data, and also for the circular buffer that's also in the library. It's used within our own libraries, for your use case, why not use regular STL, which is available on most moderate-sized 32-bit boards? 

I'll try and take a look at this and the const change, to see if there are any quick wins after I've finished the tcMenu 2.3.2 cycle (which isn't that far off). There may be something we can do, such as providing you with the ability to override the function that gets the key (where we just give you the raw pointer) or something like that.

**Comment by davetcc** [comment]
Suppose we gave the possibility to set to key accessor function, do you think that would work? You can see this in the link below..

https://github.com/davetcc/SimpleCollections/blob/d4eda9c2c9f4c515650db1f464a48ce8bae1fac2/src/SimpleCollections.cpp#L37

**Comment by NachtRaveVL** [comment]
Hey Dave, apologies for the late reply.

Honestly a key accessor could work, also. I wonder if there is a partial template specialization that could also assist in the case of such pointer shenanigans, alas. Probably something best done on the user's end, but yeah, a key accessor could definitely work.

An actual hash table implementation would also be nice for that O(1) lookup, but that's a whole other thing. :p

**Comment by davetcc** [comment]
I think that the thing we need to remember is that this has to run on anything from Uno upwards.

The main purpose is to provide some very basic sorted list semantics on a wide range of boards (starting at AVR). This means it is a compromise of offering far less than STL. The more that gets added, the more memory it needs basically. 

Adding the const and the key accessor are basically free but for many pieces of functionality we could pay a heavy price. 

The reason the template is only a shell is because of memory usage on smaller AVR boards where the compiler didn’t seem to optimise their use that well.

**Comment by davetcc** [comment]
I've done this and committed it to main. I'll release it once it has gone through quite a bit of testing. It would be good if you could try the code from there.

**Comment by davetcc** [comment]
See the documentation for the constructors, there is now an advanced constructor that allows you to define the key accessor.
